# Generated by Django 5.0.6 on 2024-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_description_exam_duration_minutes_exam_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomized',
            field=models.BooleanField(default=False),
        ),
    ]
