# Generated by Django 5.0 on 2024-06-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_question_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='randomized',
        ),
    ]
