# Generated by Django 5.0 on 2024-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_examstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='graded',
        ),
        migrations.AddField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
