# Generated by Django 5.0 on 2024-06-20 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_exam_graded_exam_password'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamResults',
            new_name='ExamResult',
        ),
        migrations.AlterField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='FillGapsQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.fillgapsquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FreeTextQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.freetextquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.mcqquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.truefalsequestion')),
            ],
        ),
    ]
