# Generated by Django 5.0 on 2024-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_fillgapsquestionsubmission_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
