# Generated by Django 5.0 on 2024-06-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_exam_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_tab', models.IntegerField(default=0)),
                ('exam_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examstatus')),
            ],
        ),
    ]
