# Generated by Django 5.0 on 2024-06-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_examsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_cheating', models.FloatField(default=0.0)),
                ('time_no_person_present', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_cases', to='exam.examsubmission')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
